# Use root/example as user/password credentials
version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: xmd2acx.qkbuhe1ECB
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
    networks:
      - api-db
  api:
    container_name: "currency-exchange-api"
    build: .
    env_file: .env.example
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/app/src
    networks:
      - api-db

networks:
  api-db:
    driver: bridge
